In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("./Bhaktapur_Dataset_complete.csv")
df.describe()

,LAT,LON,PRECTOT,PS,QV2M,RH2M,T2M,T2MWET,T2M_MAX,T2M_MIN,T2M_RANGE,TS,WS10M,WS10M_MAX,WS10M_MIN,WS10M_RANGE,WS50M,WS50M_MAX,WS50M_MIN,WS50M_RANGE
count,1.424200e+04,14242.0,14242.00000,14242.000000,14242.000000,14242.000000,14242.00000,14242.000000,14242.000000,14242.000000,14242.000000,14242.000000,14242.000000,14242.000000,14242.000000,14242.000000,14242.000000,14242.000000,14242.000000,14242.00000
mean,2.770000e+01,85.5,2.05008,77.974535,7.766868,58.585754,12.86055,3.314009,18.587044,8.536149,10.050925,12.494514,2.225029,4.934188,0.443803,4.490323,2.200087,4.277611,0.577130,3.70052
std,7.105677e-15,0.0,4.57245,0.277005,4.618868,23.220044,5.13351,9.283701,4.521344,5.436674,2.790174,6.712139,0.488554,0.934458,0.283536,0.894949,0.532383,0.985093,0.372253,0.90814
min,2.770000e+01,85.5,0.00000,76.930000,0.830000,6.130000,-1.42000,-18.160000,3.590000,-6.390000,2.770000,-4.250000,0.570000,1.060000,0.000000,0.920000,0.870000,1.440000,0.000000,1.00000
25%,2.770000e+01,85.5,0.00000,77.770000,3.560000,38.522500,8.42250,-4.820000,14.990000,3.960000,7.860000,6.280000,1.840000,4.260000,0.230000,3.850000,1.800000,3.570000,0.300000,3.04000
50%,2.770000e+01,85.5,0.06000,77.990000,6.310000,57.045000,14.08000,2.715000,19.350000,9.000000,10.170000,14.180000,2.170000,4.880000,0.390000,4.460000,2.120000,4.180000,0.500000,3.63000
75%,2.770000e+01,85.5,1.87750,78.180000,12.790000,81.687500,17.44000,13.270000,22.050000,13.790000,12.120000,18.430000,2.580000,5.600000,0.600000,5.150000,2.520000,4.870000,0.770000,4.28000
max,2.770000e+01,85.5,81.86000,78.880000,16.690000,99.680000,22.17000,17.450000,29.140000,17.340000,19.000000,24.920000,5.080000,9.560000,3.250000,8.420000,5.780000,10.300000,3.870000,8.84000